config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'about' => 'static_pages#about'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :programs

  resources :players

  resources :users

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/program.rb
class Program < ActiveRecord::Base
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:grade, :type, :dates, :times, :venue, :county, :coach)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :grade %><br>
    <%= f.number_field :grade %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :dates %><br>
    <%= f.text_field :dates %>
  </div>
  <div class="field">
    <%= f.label :times %><br>
    <%= f.text_field :times %>
  </div>
  <div class="field">
    <%= f.label :venue %><br>
    <%= f.text_field :venue %>
  </div>
  <div class="field">
    <%= f.label :county %><br>
    <%= f.text_field :county %>
  </div>
  <div class="field">
    <%= f.label :coach %><br>
    <%= f.text_field :coach %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/_index_of_programs.html.erb
<table>
  <thead>
    <tr>
      <th>Grade</th>
      <th>Type</th>
      <th>Dates</th>
      <th>Times</th>
      <th>Venue</th>
      <th>County</th>
      <th>Coach</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.grade %></td>
        <td><%= program.type %></td>
        <td><%= program.dates %></td>
        <td><%= program.times %></td>
        <td><%= program.venue %></td>
        <td><%= program.county %></td>
        <td><%= program.coach %></td>
        <td><%= link_to 'Show', program %></td>
        <td><%= link_to 'Edit', edit_program_path(program) %></td>
        <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Program', new_program_path %>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<h1>Listing programs</h1>

<%= render 'index_of_programs' %>

app/views/programs/new.html.erb
<h1>New program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grade:</strong>
  <%= @program.grade %>
</p>

<p>
  <strong>Type:</strong>
  <%= @program.type %>
</p>

<p>
  <strong>Dates:</strong>
  <%= @program.dates %>
</p>

<p>
  <strong>Times:</strong>
  <%= @program.times %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @program.venue %>
</p>

<p>
  <strong>County:</strong>
  <%= @program.county %>
</p>

<p>
  <strong>Coach:</strong>
  <%= @program.coach %>
</p>

<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>